language: java
jdk:
- openjdk8
services:
- docker

before_install:
- docker pull openjdk:8-jre-alpine
before_script: cd server
script:
- mvn test
- mvn clean package
after_success:
- if [[ ! -z "$TRAVIS_TAG" ]]; fi
- docker-compose build
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TRAVIS_TAG
- docker push $IMAGE_NAME:$TRAVIS_TAG
