language: java
jdk:
- openjdk8
services:
- docker
before_install:
- docker pull openjdk:8-jre-alpine
before_script: cd server
script:
- mvn test
- mvn clean package
after_success:
- export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH--$COMMIT";
  fi`
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker-compose build
- docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME:$TAG
env:
  global:
  - secure: CxHKymFB0Mk8JZOTtJdXopQGiZlyHdKHcJLTar/ORG2Ld0Cbz+1f+wHZ8uo+ycK+lpqBvp/GEQD31mzEd8/I+p6X8ZeSO8fmkhHUtknXshSo/YxhtmQ6vuLGad7pLL+zLS+t1NtASUFs7HfywdRG6M8AgldJhGapXSO6QdzV/CTz4Cm0EYoXmxA1kOmvxHB8jwAbi98bh4h5+pz2g9+B9xNruG4BmzuKrvUPzM/P5Hcwo1jtVYWeddrEVEYN+er6KAqzSgUb9ritbSA79Jyoa9LXCWEL8H0hIc15tsWzfQPSuYUWCOf2iAT4kq3jM5nx/4ngdOcT3bTuYBzICg9GSmVW03fyEZPrUvI9SwYKdQ3EFJ+p6cHyrhx/D8NtOXjyfgMKxQXInCeRzCh46NhypPJrqqLIXy3iAtt26mT0fmxNPV+gpgBDThI1HyYXTFudXA3hZqJLN9jzgJA36ogaCJ7m7C5VTm6tvtL+VfV0YVy3UMLzojFxN6LVsX9q42rQnl7lqvAao2+U6YJIa51ULhJg9fTiaGoJ700o9sWwq0Bhhv2eXG7DX/6VqvY0m3JTqsR2QvWQnbsXHDIcddFEoAAhHg2tLsE2i1EtPnhCaj64giI7sy/nLVv+JGEl08HRsQJ5DjuUIMhj6ZKychVLdRwAdqkwvL/obAE07piGT44=
  - secure: IhKMydPAZMCRTotuDi6qkZtuLiRb18ol4g4yOBve7+I6otvrppNxgVai4nAOtxYxOubwVxyxOpikN9G4ho9BVD9MUHG8WG6mnHkyxxBIwjwDAgGOF1eSYjtcc8hQ0XaXfYmiZO5F6xg6axZolgeF4f0Qkba6Gp/9lIl+hSRQTevjmhk1e1EXAzeD8fBbsutPsS1V/dE6uv85DYVwFdEUAmHTZkBYmLfbQ2xE2ZXyaYPGtH8hg63F9CDJ9cUkCXYa02RDhw/Aj5geqKXhghoWMrFLBcH3d0a6nfqfo8ZnZFUkdnxFAiL8ZYwcVzBh65Mk5C4acjzCgdTaottaLYRfgc3SCxhc1xi4q4knse4lIRUA232HrC9ThIJbQzeSq80eU+D9f92QbxHrxdHInL0erP/M31JsgdfPqfeSB/6UOk6ErmZR6hbJQzOgdSuTzs0gVD+WSycmwspAXjugr6yFP3xfHk6j72B8r3LjaeK1KR37xbQputOnH2bcODAtscSUMuWtvb9cDm+XSxFKhme7VS3mncb3Pn7ZXVGpqPst0+5EyUyCKU8lYbVo6fErkkVNx8Mzu5aRCBqkXFYSL/flEt+zMkYIC70quYcpl2HnSF+ry+PYcxDjpjfE/GN0kySWt7SJ1L3EY/hHMY/KnH4Dg7Qk1O6tbeilQrAP4Kw87rM=
  - secure: HIAzFL3sYr/Qyb0x1K0Ktj3ZUqdAR6Wdbh7DUtT8sB7YlI17Hz4IUWvxViucYuV0G5+xhc3Zd8d2wirBM/vE6o1DhZv2+NGoCnANZfTQ3b+5+KI0R09OvRSW9cnz5tTteWBE+l0lgX97bHcTd+ROKMuxjKtS6Ez3VYtWo0Nvm71tFTAJRN+dpKvzExm+/IN+7DAKpV0Mrq4kTX6v8+0KmjNxuTxxD0fobRXD6+X0iTUYgMzbJSHaOUizh8LiguUXHcH33hhXRkgLyX95/6j+owlOVZ9biQTvG4SIzLkOPHVb4fZ3hs/lIseqT6NII8IwxIyX7ME3qSgPar5gjU/SX3KdU2iiTgGBHf4ph8m4nbSuCbns51MNh/uxnfgiE8i+0fNw+4U7TDYbiF+yevgvKTofjXUD8vH37DNH8AJMyGjfpHCgenIr3+oRoRFcpfrBbRq8VEUdiSd+ECB7uaycocduD/9pWZ5oA+6MQyx/5n9rNV/StD2M3B55uvi3eca0ClCj49qpVDHCh6eK1tJKTX9cmFyg8b6u+OM33ORoe6clPHGq3UCqBnL9iEHQXqsNN4nKuhQHIySQAQ1QmFsjBOqMsajVbv/gCOLPQzu4LmHZBjpY3fj+D5o8kyQjuYipwWCMLYdgTw5B6GUUge8y3U4AuZ0+7mcSfWeYvKskfVo=
