language: java
jdk:
- openjdk8
services:
- docker

env:
  global:
    - secure: 'cKttdbtmvzAFkF+i1HDllWOq86tV6/EHOOs7kOGwqeY4VvtQDlAnSae/7p1lN+ZIj5MB7jIF8CxRGTodewWtLVERsicJvM0UsUB0rOVG6xl+RPsazjSR6drf8JtWxZiJDuAfHTj2J6eq5Z8+IhT9H+SIX20LbvhfPB+BPN5bxMn5J8WTLbMRLam7YYY4JLhUrfwwFenilelet2Onm1zh4cd49ZSg+4UNtz7R1WN3hYAISKMv6L4ovhrlRMADmp0aTb/orMe+XOmtW5OyTMS9DRAE9Tqq+/p2c5KAGY0BeQjgchqvVM078WU40FCuubR42hJ416TaReub2M/jDjFJV0amGH5hYqqYyXXBn01zay7iy+KcjD9nQLJa0OBFqMMV1k/qwfOP1Xv9RMtsItBVv5T7OdC0Wl3jqpRtilUcw/7eMX83/worGgNq1kRyba5+62u606sxn5SQWE7mStFQar7y63/VQiIke9XBVBKrI8qVH3yQLoRgZS8YRU/OLczrNjxDwkG55q0DYqsN4BuZy2qy+IcYomXt5H4YkU078dQH60Ls+S0aI2MKp0ePomoUuUTD3if3GCpo2RFL3E61xCI5PXQUbjrmYflYCAc3KXjeczcEqrRnkUe3nA2eREkMiO23BINpa8x+c3VeJvPcIWmXK62OVgAFPrr+xI7HVVQ='
    - secure: 'UTS6166GlubMcbUr1LP7f5VfcDiuh6JIPET81I2jmZbu0+pKpPdXImQSU4PrVYS451Kg14dKNABa5HwNKShQoaPAmOAYZ33uEORzZzRVeE9ZBgzMIupZZ7gAYcWUHcZZDIAaYlC6JvdUcuHrx8pQ3Xty0teSIToRA7JRZPSJik0NYLihAIzTcF4CYPlGHfFkHutWQKR1yoB2vdeYv/LRXnLEfv5j+tEnH9jR8yQq3ygnAp+X6Ua84xAJWSyyLR2UpNnf+twt3gJ5aRWsu9egiN3UPU4m/JZgzw1U5EFyVAwXvPTBb89KxRAluF0tPTLb2XRvtfDK9xyXDzfI855nfcDcTmjGgYl+4trYSXHAiShbp4PkjiZSI3t8D2m+LcVy3tg+KpiPBBCB4N3XB3zCxawEsPs35w/ixHv7C45o5sZzy7XxYRwxZTmNNBh75FlvEAmVEbAAERMe8JIYKGK3Dhb6XrojoQnhdEjks9vaRE4gKFMaw3gSJpmk6nFPzfcMp1YhLH3M1lXs3mm5ON3qXNOaBYmOcOJAo6SJUZeUic+E0Cjce+wWd3dLK2ggVLOd/MudxyrSm4FeSqF3v53zRlMgngFXI9iguaMx60Uue8YQjSodqKP9+hB81Bp8n4+xhaIjKLNES61Qn7LYP5MK2EOym7Wh2dNgOk/1ePBakRA='
    - secure: 'bgMmPRcH8mskSsNKq/OJgo41+j/eEhKx4ZDaoU9AmUAR/2uCNph5tPDTa1saYqQ/JZEgztltWx8wYgtlO8RkvAO5Oo+/MaIj6Duw50mNQW6CzKtK+KkNsJabNVUaQBOlGoT6gOP1YC/4Trv0TZ4i7cFqJiH7S/57Oc9iARK5dXNf2uyrLa1q5Q7RiNy/gJXMTvkTxXVU50L3N4s6SeoNjX92Lsj4KVLweaCLFCxeqo8hWWZnrocT3h6Ol9bbMkYd8O9fWNUVGY9nTRP3oWqSUa98Iy4YsuKV4s+v/0xy4qVFcgnUf4gSGZc2pksgJ1hGryGEw8DSdV5sVaDmjwDZB9af4909AXQ7sn6CpE3c42LFLy/lrj0o0sf6zHomDuetRv2cG6s9x8jNS08zbHtQVo2Z3hUEYTC1z/ZI0FP2iLGGtiuLHMQcx739qF5Whh3Qgjkfhsbi5/MXOswzv6HMVkKlw2VfiRoOtrwY9667CHibEn0ZUVu3zNtl9TtEWNwm3xkONyV86hTgjwdBkCSamDYAbLAexiycVpolxIcR2txcfXb9mUpLu3eoykrZzPz93x7A3z+rqPLebpOIgVK7/jUPpiZJ/dLEQZjokf+b5sZskpIpA3D/7AvUAsfXZOIKWzZhR9SOJEdGnmM4mUbJYsHjVgPbQjX4x27d5jg3VP4='

before_install:
- docker pull openjdk:8-jre-alpine
before_script: cd server
script:
- mvn test
- mvn clean package
after_success:
- export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH--$COMMIT";
  fi`
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker-compose build
- docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME:$TAG

