language: java
jdk:
- openjdk8
services:
- docker
env:
  global:
  - secure: Y7TtuSLomj0QGnweRSFVDH4daGsNyWPeLGIPPDWpdnBNmVJwQQlPCbBTk8r3B08EAuHGaEvc5tB+D6INTyFvR1IoOw+nC6TDyL+ER/xyaQ0ezeL5ujtwuzb8/nrPrv/xIbh6GXq3KBrMNO+5RSFPcM07YHO1b3T/hbLF9ejAKzN6oO09pNoCG8/5ZdrAgS4V9ZNPQAbNJ0dvsLAxP1bPWMlGr5swMewoh1TLd9LTcHhLsVxweEvcBqvfQJfw0Ny+wBkEqMCQlWGvjseseoyKHAlJffntg6mzslAcXd6OswXG8Y1S+4OjpmASICtOmgSq6rPmute8FWVM906R5zG4wng3h8SAeQ2eCYvCpfF700laej3ViTycTQOhlznQ7XEwXCsrCp/r7EK//iiEfgilrn66EJaUbg9iTJC2ns8xcte5gNeeztEME677I4P8PlBUoa7Sj51sTTn7YoshBZg646Rna0BpknLQFOMSp4U/q9mlfUKtPuqgv62Gls36YjEa2vlOficwkHokvBGISnl2MSQCOmHirnYHBairgiFcGqxDIUPJmHB8eb0bNNNur7L+cZxFFkD3W+m89tSF0sr6XuCI+rHn6jAWS808KJ/4eaFRicFmFvy9d1zESyXHViejCSJriJm59vPCOBcyRAn/PPtOppTrrZbfuyHcC5/Mdg8=
  - secure: fm+Qf3p38snFzYB744fIiLyRmUmyBvZTSPFL82GH8ovZ8+FC2RlAbwpWdXZj1NiHBg+JiBDxCv6WhCV3wnrif0mT46Fr3zzorpVzvyVH4rYwMavxeOLCGnh2o4/ezqOo8tiTN6OQHyPRPb90g/z/9/pWHUvhxb+qGs0kTH2shGE2ib2z+dywOEX61RuY7J6FySejV+qNjW/7xJhla7cvk3VQuoA2DRfbWoWL4nrzZvsF7Q7HoOwGGORjUwspv47r47hG1xoo/QzzjTCnG60mpOHOQb0462DTh5PnY5JnsB5dmN3jCpyO/RSi3V2thNVw0jmwVDr/afxI6vIb3cl4R5Hyg5jn0rzFYvxy+SUrg+lnf8+AzoM7qrwi7UtC2TwsMywy6PgXCGGDFs2VcDI13Mj6ZnZv5fgPbiw2nEwfdQv0zts8K73H9WJhcUq8QOF47COGVJVfS28w1rZtsUKjoTWPW+bPVWAiqD5n0GmSVgcE8reOPP2MrIYVDaW97/6RidN8NXGsnfA37A3/D8b8vuKv1I3IgLTLhkXpR+hVLVz9RCVj7J6C9DMMhH1lA+//3BZMiGeoN8f89sFX1xzahkWupJOImsYvhmoQWGMDqPgTzxfqXZpL+VNcyLxYZAJMb+h4HEJt+dyH3Y74SMgbYsaMkH8xJIo4iH4QwXXq1wE=
  - secure: 'kykqvFQXrhpMc/RLYrTqqYVtjfUtGHNViwphssfevIVGwtggGT/arSB9+2CZAmz0XParwvLA7r6LxEPV5xsiN8qniBIOLsriFvNT/7bespp2VLI1V+vYsQwse1/acPTWUZJf8F37d9kyUN+PjemVrWBnAuFHn86WYTLBw1IvGdRfY+zZLFqUXEk/zLBIZNStYQsMJu2K2fjrY75JE5w5I8o2R7tj/h92+/kHhFhyKTMfdEBynhHLZVur7zS3JmOER8Lb+ubzzLSg3eA/QxLJ/MD2VnPwKnAWBtcDun3Y3oAZtQXp7K7n4I1lRrI42PEECfE220eCljKSd3g/+lIJr6rbkkFPKKz7Bjbp3rwoYleFrZWvidw1OAWpqpSFBkQwp8JmJQwSkqsY3MO8IWpOZKnBZord8Z+CT1JxaIke2kIArf5znmMRgUR4Qm1sGqs4uwAj6OCiF26gac3iRZYV78dTjoxEWc7sbboIWcgRLdK9zuAfBJRpFJXkjhPEXIrcenelebut+oTvXsmE4VOddbMuiih8HbV/Lld0DWyFLGZ3N9FXOWtkidrGjYXcd/BuakCfhahtpPLf0GO/i4opUFJK3nX+1TZn6bZcBq90bqlMxFjectQbQ8wNU9XPmGfSy7cfPFFWTOEwcmjtNNmzhPGXJHUbbchPT5tOpXl/Yn8='
before_install:
- docker pull openjdk:8-jre-alpine
before_script: cd server
script:
- mvn test
- mvn clean package
after_success:
- if [[ ! -z "$TRAVIS_TAG" ]]; fi
- docker-compose build
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TRAVIS_TAG
- docker push $IMAGE_NAME:$TRAVIS_TAG
