language: java
jdk:
- openjdk8
services:
- docker
env:
  global:
    - secure: mbUKdMTG5XTHZ+onZwG9JPHdS0PbsVn8hA6qp4CSC3u3Ayg/8nGvAQZooGURsdbr0UpMmgKTEi1/i6owQHqDXpgICtWclX22D8xcieHFSPcb2r+7iWNMR4UApZu4esGRtAzP3flSp3n5YzT8HAgC0Yme2Zla69BOh4zGww4SAPoIz0rut4Jr9MRNqqmQ0HKSRZakZt1CGf2TaBknJ9oW2bFEcStiqoNL9fX2hoNau6j6YAZf4Wjvvh7Br+8Sf67RTVcUusfgqVnssTPutC1W0F9NfRW3AdL2nbOTDQPwRcDPGYZrmwmVegaHgr302jcIBrvGxWh+cDi2YgQsiWLXF/5w9PVngWJSe5GhOuK4Ha5wh1djXHPfW2EXm3uWiu6/+E1lLYqB68cgZ6dzkpLpAATKK4n8d9jns/cF1vqIth5zYmIXxd0z29SfqzT5deuhCGHwhDNEy+94OE+iBGm1lVD0ciN5h/p6QuB79jXMtNAtoLWE8bJ6i0niZ0eIYKYlriiGWZjeB2cdlAjXdviGOBTqOekrPM0FiyBXZZZ/JhtBcu/wu9CP8rZ6fiMF2KrxD5RJHzKpngTaAuFWS6iTAESKGtS2e7FmSEe8N1qn+hfbFc9+uMRx4PNaXB9h1bXA41r6DuJy6K/utVqYZk3LcaigJ9LQsRxH4k5wYb7Un8U=
    - secure: 'vaqqwrquzDL5dIzabBQ8yV5+LVqQENVkNKclpBT2wQS868HWly5I4P0NQuQBlI/ZQH+5RJ3unWCvdcUPsXsSMyO4jvE5datVKsYhQy7QapxSKFEFj0XgI3UK3ADsSNVh8DCEPC2H4zAlFrbxj/rlJNkzUXMuqCz21MYCnXNvVvQQZfxOXMosm2BwvW0SPHiicL81Yr2E6Fps/+TQ+jWuEfKmGwuEATBcj1fMZAiFnA+kHiSJHXIhP+T7Fuvo8uWSK/Pa4k10lA7e6TkNpjatUTY+asqF7nWxK/o4aSQOhC1/6sIoZwPciJrgAxPxElDPmNbw9UuAPY5KkXEcjU+wtpmNLEqwkgpXx2Q1fo444pKBlht/7hFPCCEGAPwF0bRJKaQcyBzO+n86rxy3umdACT4Ktdb9M2vVJAHQMDjOBXlcx/J2/ikjaTG8C8pHnl2syQ+2GseWKElmkOmCky19oSLUvN5w7Kvdb2U9Kbusz43Atrv/e7z/+D1nYef7HWSZirXDh+gFolGoGsPJW47NVClGL0pJK/h9azP9W0KII2xrVwdVGky7UqsIE3tQmmohHsiGSlXuPiUWqiDe+egsr6hDv7M/cIVkcQA8eKOu6mj/SbcVvrE+a281CQ1gxkcY7aN/57KGi0L9C21fe6s2hjRkHFxTMAVr1IJ0k2M7r4E='
    - secure: Al2O4CUNxbJLtYSTawh+qQ34jsw9GlQevcVD1AEPCl+j2zSeNegrSi3ftQ9Pr8Sx/DIsT1O9pQRIlIiqfKDUf52nve0jVH0aPA774zyPPKMrqpZSeTVU+sjSCieyZs7DHX4S4ezTg5mofK0MQB7B2ZOQQWQvMZaTGoZAwPo1lCf/fgPXgqbHkHhibNzlTFAAqFzN3FIV4mg8/IFD3guCLdDpf6bIdVpbPKertYqKImxvBHY2tHYGCrrj9stpSw0PNfxTHXCC4OkI/sylF96LuIYNK3WffpVTF7A/zh336T0wFqWhGgNZtSBeILySZMEYrGzWPqSZ0arAoBmJx70TbVgj2YkZGVcgOL84GXaAiPIMOTx94X9zaAHIdQ2QTYRqOM9guxf5UmJ+P8YCc+8nVN53h9QuWN1APjF6ldFzj5R1hklq0zFHKSA414s9ZvRnXaTCm6a8jfqKEBs8hLN691ExI7UwFRzyolx/Xji5owjLQH/ZrM+Z9qnjUewjpifofCZV9hBq3fwX2PRZArWDCxNHrzmA67Q9agXWE828FdotqQrlQcokqtUW3PNB6+mgc9R3jAFP9sz0K3DFxcuqT397ogrormnCEMqvngevjeMmEHNEv0uFaiAW4fgulFSMujU3KtzfAafMuIDra1l5yp/npjAf0Vn6FMXinvcbpt8=
before_install:
- docker pull openjdk:8-jre-alpine
before_script: cd server
script:
- mvn test
- mvn clean package
after_success:
- if [[ ! -z "$TRAVIS_TAG" ]]; fi
- docker-compose build
- docker login --username $DOCKER_USER --password $DOCKER_PASS
- docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TRAVIS_TAG
- docker push $IMAGE_NAME:$TRAVIS_TAG

