language: java
jdk:
- openjdk8
services:
- docker
env:
    global:
      - secure: K7u/adDsYclhCz7K/WN8pV4gLDpV+y5PyUdBZeGmme0wlISoe6G3aQsZ/mZrsdawO+D8a/xeqfaBGCwa2Un9/uFGebQg4H8D/wwSH5iIYGS8ukBHKGJsxrEX7WNw3kbBN2+3KivMbTD455/raNVwNMtgALc87VUZCGswCjydVzF5ywWK4vlU7M2Pcbtbp4vnk8Z8hAvNjS4I4QRIb1mzeFxFEmxVs1yyNI9qUrObtK+YybDAtHOD/gLQ9z8tcSgWKnmx/L6W4UpqOcEWgwkyp64sSjWJnoqhtVmj7wEwuBild8LqDezxaX8IojN6MkGe1lAOdopJLKytEnuxhXosBXero4Ndh8ln/plS/0nDYZYUu8cYQVRJVn1QpI0a2GZ5Z19wh7Cvm3YXqvw092DBYbO6esp4jhffSupEwlvTXhM5uMEy0LwO6ez0uwRrIcAgo6zLlP2uA3BeaMQd3Qe0PDHdclFjFg+EE3NEFltScvUMOa6451ZEso4jb/lpmJaJcS1MQqHm800kHdfwY1Hg8twNiSt4jk5f3Qx/02mBX3ni1NV682w1lAjulJyNdFTLtL5mnrZQmu6fD8obyJ0LY939o9J2iKXN7yo8IMUmLnMLbYWCqKXur1ENm3N7s/7xABcZGjucN1lO9nN4IadiTbDBHOTGb5DO+Y9aiTlRPa0=
      - secure: 2yfNgnQR8rTiYnjmQZDsE22jNOPlzOjufYTlRg5gubXLPxZbcrsg5iUsF3k+J8HkJwETFDClwpHCuSLw0O3Dcfp3OsxtD9R0cmrHLUxYyPJLmAn8VxaywfBffx6bIWe9DzIoOMXAdqGHbv8tBnbJyaKll1XYBiHm/XPIEceqx27kBaznnzkeGQFLiV59y6mw0QZ1afR4lewDd7QPzZgPgC/DWhQH+s3ftlmePPOg9AW27PdLPMRYtCzrT0yWpI0WKZ9OGhcgnEBQU0RcRh9MIPwlCGpXvSqJEyEA6HtFoiU9eHm3bbiONQCmhvVZzySPpXbnYDTlS7eTyQgBXOcpFjHqVX6EN3Btu0DkOSMC6sdvNCtx4zeV56PZJPYt+7nzLSDJ2rBmULVnLFqfPqYEMgmJkI8F6e1WMn6iHNTkiOZ5xzdd89qNhlFMbd7Nj5KLsRLR8T4a/nEcDlNUfX/A/JiWdraDqiQfCfdXTmsUj/Fc+vMQsMsYsDH4ecQHXcYC3tqo9du23hSyf8fPSixC8jAhESU8DQEs352aQZ/Uu9dU0B4s7q5EugaK430r9nCaBsDbCVviZvZCWRNRs8SnrV4ndM/W9zkH01RTJp8wndchg6RqcERota6UQMWBSP59TlBXZ6IuUZ5kFnUYuKFJBu2Iu2X9aquujDApS8VvyoA=
      - secure: HSz6Et6QnFgXUFUxTTEsPNqzPRmkC4ZhhMbdvAYunX0+C0ek+vKCRxtlR0Cc+wk4Z/YEHSS4PqrpdUOrCc+46rOAmtE42yvZnI7Ud0It13PD/RNtrnoELyYApd/p7CjUV68ny1L7CzF7LOD3qcztnPhLmYgMz1q0R9bchw+ObrIN+Q65EMDXD2LDsp6FKLAduB4y070CD5kldo8PXV5sr7N+kdWP9Ex7Pmi/9pfG0fla5l7/xP6KC/266ikAaMucGD6NZDuDehzXAm8T5ZJopHwLZsKsQ1DElcV8EeQqZlH4Zwr6ARVgJZdNLye73s47eA4ihPulWBaRLUWBfsvs3FJdxRvavqYv4Ff7bKEV94KFoVvlXHKT8WMOpU5+vKCBvoQnJyt/l9bi4XKq2Q4vE/SGPaAwzPNImnKYpvR40lzEWgEod0tbXpjK0ldpgQHhpyN8uniCTU/O1nUJAjrXvgJfjuxQ/OlDD1GJN4j+yf8QJYVat5ZljhlI/Bb6qlnbMSMo/gROzksGrvFvBRGsPYDJofsz8uVF5wV/ghE6OLmatvkQYyQcxeWIn5K9cIkr78aprqZptEDGbdjTg7h3JGlLa7rOaG/1pcHIL0wf8QaoZNeckxCr84nVUw4jHUtaQ8dgxcKAjcWuhwXesEyFGzjcAElwMp2MLTKh2pStVb4=
before_install:
- docker pull openjdk:8-jre-alpine
before_script: cd server
script:
- mvn test
- mvn clean package
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker-compose build
- docker tag $IMAGE_NAME $DOCKER_USER/$IMAGE_NAME:latest
- docker push $DOCKER_USER/$IMAGE_NAME:latest

